version: '2'

services:
 database:
   image: hypriot/rpi-mysql
   container_name: database
   ports:
     - 3306:3306
   environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: spring
       MYSQL_PASSWORD: root
       MYSQL_USER: root
       MYSQL_DATABASE_PORT: 3306
       MYSQL_DATABASE_HOST: database
   volumes:
     - ./message-boot/src/main/resource/schema-mysql.sql:/tmp/schema-mysql.sql
     - ./message-boot/mysql-init.sh:/tmp/mysql-init.sh
   restart: always
#   network_mode: host
 message-boot:    
   build: message-boot 
   container_name: message-boot
   ports: 
     - "8050:8050"
   expose: 
     - "8050"
   depends_on:
     - database
   restart: always
#   network_mode: host
